# Generated by Django 3.0.6 on 2020-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research',
            field=models.TextField(max_length=200),
        ),
    ]
