# Generated by Django 3.0.6 on 2020-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0002_auto_20201009_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research',
            field=models.TextField(max_length=400),
        ),
    ]
