# Generated by Django 3.0.6 on 2020-12-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0003_auto_20201009_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
