# Generated by Django 3.0.6 on 2020-12-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
