# Generated by Django 3.0.6 on 2020-12-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0005_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(default='Prof', max_length=200),
        ),
    ]
